name: Expense Project CI/CD

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push-frontend:
    name: Build & Push Frontend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/expense-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/expense-frontend:latest

  build-and-push-backend:
    name: Build & Push Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/expense-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/expense-backend:latest

  # integration-test:
  #   name: Integration Test
  #   runs-on: ubuntu-latest
  #   needs: [build-and-push-frontend, build-and-push-backend]

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Backend Container
  #       run: |
  #         docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/expense-backend:latest
  #         sleep 10  # Wait for backend to start

  #     - name: Test Frontend + Backend Integration
  #       run: |
  #         curl http://localhost:3000/api/health
